export const FETCHING_MOVIES_REQUEST = 'FETCHING_FILMS_REQUEST';
export const FETCHING_MOVIES_SUCCESS = 'FETCHING_FILMS_SUCCESS';
export const FETCHING_MOVIES_FAILURE = 'FETCHING_FILMS_FAILURE';
export const FETCHING_DETAILS_SUCCESS = 'FETCHING_DETAILS_SUCCESS';
export const FETCHING_DETAILS_FAILURE = 'FETCHING_DETAILS_FAILURE';
export const ADD_TO_BOOKMARKS = "ADD_TO_BOOKMARKS";
export const REMOVE_FROM_BOOKMARKS = "REMOVE_FROM_BOOKMARKS";
